export type RawProduct = {
  handle: string;
  title: string;
  manufacturer: string | null;
  category: string | null;
  status: "published" | "draft";
  discountable?: boolean;
  shortDescription: string | null;
  description: string | null;
  thumbnail: string | null;
  images: string[] | null;
  priceVnd: number | null;
  variant?: {
    title: string;
    inventoryQuantity: number | null;
    allowBackOrder?: boolean;
    priceVnd: number | null;
    options: Record<string, string>;
    manageInventory?: boolean;
  } | null;
};

export type MedusaProduct = {
  "Product Id": string;
  "Product Handle": string;
  "Product Title": string;
  "Product Subtitle": string;
  "Product Description": string;
  "Product Status": "published" | "draft";
  "Product Thumbnail": string;
  "Product Weight": string;
  "Product Length": string;
  "Product Width": string;
  "Product Height": string;
  "Product HS Code": string;
  "Product Origin Country": string;
  "Product MID Code": string;
  "Product Material": string;
  "Product Collection Title": string;
  "Product Collection Handle": string;
  "Product Type": string;
  "Product Tags": string;
  "Product Discountable": boolean;
  "Product External Id": string;
  "Product Profile Name": string;
  "Product Profile Type": string;
  "Variant Id": string;
  "Variant Title": string;
  "Variant SKU": string;
  "Variant Barcode": string;
  "Variant Inventory Quantity": number;
  "Variant Allow Backorder": boolean;
  "Variant Manage Inventory": boolean;
  "Variant Weight": string;
  "Variant Length": string;
  "Variant Width": string;
  "Variant Height": string;
  "Variant HS Code": string;
  "Variant Origin Country": string;
  "Variant MID Code": string;
  "Variant Material": string;
  "Price EUR": string;
  "Price USD": string;
  "Price VND": string;
  "Option 1 Name": string;
  "Option 1 Value": string;
  "Option 2 Name": string;
  "Option 2 Value": string;
  "Image 1 Url": string;
  "Image 2 Url": string;
  "Image 3 Url": string;
  "Image 4 Url": string;
  "Image 5 Url": string;
  "Image 6 Url": string;
  "Image 7 Url": string;
  "Image 8 Url": string;
  "Image 9 Url": string;
  "Image 10 Url": string;
  "Image 11 Url": string;
  "Image 12 Url": string;
  "Image 13 Url": string;
  "Image 14 Url": string;
  "Image 15 Url": string;
  "Sales Channel 1 Id": string;
  "Sales Channel 1 Name": string;
  "Product Category 1 Handle": string;
  "Product Category 1 Name": string;
};

export type SearchIndex = {
  id: string;
  handle: string;
  title: string;
  category: string[];
  short_description: string;
  description: string;
  variants: string[];
  thumbnail: string;
};